include: package:lints/recommended.yaml
plugins:
  grumpy_lints:
    path: ../grumpy_lints
    diagnostics:
      must_call_in_constructor: true
      abstract_classes_should_set_log_group: true
      concrete_classes_should_set_log_tag: true
      base_class:
        ignorable: true
        enabled: true
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    public_member_api_docs: true
    package_prefixed_library_names: true
    library_private_types_in_public_api: true
    package_names: true
    lines_longer_than_80_chars: false
    sort_pub_dependencies: true
    join_return_with_assignment: true
    prefer_for_elements_to_map_fromIterable: true
    null_check_on_nullable_type_parameter: true
    enable_null_safety: true
    avoid_print: true
    prefer_final_locals: true
    prefer_const_constructors: true
    document_ignores: true
    prefer_single_quotes: true
